spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  liquibase:
    change-log: classpath:/db/db.changelog.xml
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      jdbc:
        time_zone: UTC
      ddl-auto: none
    show-sql: true
    console.enabled: true
  h2:
    console:
      enabled: true

server:
  error:
    include-message: always


